apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      containers:
      - name: game-service
        image: sandarud99/game-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: gamestore
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: password123
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: microservices
spec:
  selector:
    app: game-service
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001
  type: LoadBalancer
---