name: Deploy Game Service to EKS

on:
  push:
    branches:
      - main
    # This is the key change: only run when files in this path are changed
    paths:
      - 'game-service/**'

jobs:
  build-and-deploy-game-service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to ECR
      # This step now runs from within the service's directory
      working-directory: ./game-service
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_GAME }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Install and configure kubectl
      run: |
        curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.7/2022-06-29/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    - name: Deploy to EKS
      run: |
        # Using the deployment name from your 'kubectl get pods' output
        kubectl set image deployment/game-service game-service=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_GAME }}:${{ github.sha }} -n microservices
        
    - name: Verify deployment
      run: kubectl rollout status deployment/game-service -n microservices

    - name: Run Integration Tests
      # This step also runs from within the service's directory
      working-directory: ./game-service
      run: |
        npm install -g newman
        # Assumes your Postman collection is named 'game-service.postman_collection.json'
        newman run game-service.postman_collection.json --env-var "baseUrl=${{ secrets.SERVICE_URL_GAME }}" --bail